apiVersion: v1 
kind: Pod 
metadata: 
name: my-pod 
spec: 
containers: 
- name: my-container 
image: nginx 
volumeMounts: 
- mountPath: "/var/lib/pgsql/17/data" 
name: my-storage 
volumes: 
- name: my-storage 
persistentVolumeClaim: 
claimName: my-pvc
